all: quick_sort quick_sort2

quick_sort:quick_sort.c
	gcc -std=c99 -Wall -g -ggdb -O2 -o quick_sort quick_sort.c

quick_sort2:quick_sort2.c
	gcc -std=c99 -Wall -g -ggdb -O2 -o quick_sort2 quick_sort2.c

clean:
	rm -f *.o
	rm -f quick_sort
	rm -f quick_sort2
	rm -f core*
